// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// APIV1MarketParserParseGetParams is parameters of GET /api/v1/market-parser/parse operation.
type APIV1MarketParserParseGetParams struct {
	// Full name of category for parsing.
	Category string
	// Your delivery address for more accurate receipt of goods by location.
	Address string
	// Parsing store.
	Market string
}

func unpackAPIV1MarketParserParseGetParams(packed middleware.Parameters) (params APIV1MarketParserParseGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "category",
			In:   "query",
		}
		params.Category = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "address",
			In:   "query",
		}
		params.Address = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "market",
			In:   "query",
		}
		params.Market = packed[key].(string)
	}
	return params
}

func decodeAPIV1MarketParserParseGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIV1MarketParserParseGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Category = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "category",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: address.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "address",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Address = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "address",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: market.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "market",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Market = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "market",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
