// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1MarketParserParseGet implements GET /api/v1/market-parser/parse operation.
//
// Search for products by name and price range.
//
// GET /api/v1/market-parser/parse
func (UnimplementedHandler) APIV1MarketParserParseGet(ctx context.Context, params APIV1MarketParserParseGetParams) (r APIV1MarketParserParseGetRes, _ error) {
	return r, ht.ErrNotImplemented
}
