// Code generated by ogen, DO NOT EDIT.

package httpgen

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1MarketParserParseGetOperation OperationName = "APIV1MarketParserParseGet"
)
