// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1MarketParserParseGet implements GET /api/v1/market-parser/parse operation.
	//
	// Search for products by name and price range.
	//
	// GET /api/v1/market-parser/parse
	APIV1MarketParserParseGet(ctx context.Context, params APIV1MarketParserParseGetParams) (APIV1MarketParserParseGetRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
